### ISSUE TITLE
Teach the Makefile to download assets (geoip)

### ISSUE THREAD

**Issue by AntonioLangiu** [measurement-kit/android-libs#20]
Add a function to the Makefile to download and place geoip and cacert files in the `raw` folder of an Android Studio Project.

**Comment by bassosimone** [comment]
When resources download is implemented, only cacert needs to be downloaded.

**Comment by bassosimone** [comment]
(But it is a critical resource and rather than downloading it with the Makefile I'd prefer to commit it to the repository and/or make sure the thing we download is as expected.)

**Comment by bassosimone** [comment]
Changed the title: we now embed a CA certificate, so we don't need to download anything.

**Comment by bassosimone** [comment]
A better issue is #64
