### ISSUE TITLE
Android traceroute

### ISSUE THREAD

**Issue by JoeKuan** [measurement-kit/android-libs#34]
Hi, 

  Sorry to bother you. Just a couple quick questions regarding the traceroute for Android. 

Does the code require the Android to be rooted? 
If not, please can you point me to the right direction in your code that how you can receive any ICMP packets. AFAIK, non rooted Android won't let you receive TTL expired (ICMP error) packets, i.e. recvfrom call won't return, just hangs forever.

Thanks
Joe

**Comment by bassosimone** [comment]
Hello @JoeKuan,

The code is currently disabled. The way in which it works relies on Linux error queue to extract the latest error occurred on the socket and, as such, is not as reliable as receiving ICMP.

The implementation is here (as of measurement-kit/measurement-kit@0721f40):

- https://github.com/measurement-kit/measurement-kit/tree/master/include/measurement_kit/traceroute
- https://github.com/measurement-kit/measurement-kit/tree/master/src/libmeasurement_kit/traceroute

Cheers,

Simone

**Comment by bassosimone** [comment]
I guess we can close this issue, since I replied.
